[package]
authors = ["poly000 <pedajilao@vip.qq.com>"]
license = "MIT"
description = "Pet-pet generator in Rust. Translated from https://github.com/camprevail/pet-pet-gif."
name = "petpet"
version = "1.0.0"
edition = "2018"
repository = "https://github.com/poly000/petpet-rs"
default-run = "petpet"

[dependencies]
image = "0.23.14"

[profile.release]
lto = true
panic = "abort"
# debug = true
