[package]
authors = "poly000 <pedajilao@vip.qq.com>"
license = "MIT"
description = "Pet-pet generator in Rust. Translated from https://github.com/camprevail/pet-pet-gif"
name = "petpet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
