# Origin config by @Kilerd

name: Build Canary Version

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [any]
        include:
          - platform: any
            os: ubuntu-latest
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
          
      - name: Declare some variables # https://stackoverflow.com/a/61699863
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Body
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.md
          tag_name: 2.1.0-${{ steps.vars.outputs.sha_short }}
          prerelease: true

