# Origin config by @Kilerd

name: Build Canary Version

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [any]
        include:
          - platform: any
            os: ubuntu-latest
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
          
      - name: Declare some variables # https://stackoverflow.com/a/61699863
        id: vars
        shell: bash
        run: |
          petpet_ver=$(cargo metadata --format-version 1 --no-deps | sed -r 's/.*"version":"([^"]*)".*/\1/')
          echo "petpet_ver=${petpet_ver}" >> $GITHUB_OUTPUT

      - name: Body
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.md
          tag_name: v${{ steps.vars.outputs.petpet_ver }}
          prerelease: false

