# Origin config by @Kilerd

name: Build Canary Version

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [macos, linux_glibc, linux_musl, windows_32, windows_64]
        include:
        
          - platform: macos
            target: x86_64-apple-darwin
            os: macos-latest
            bin: petpet

          - platform: linux_glibc
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            bin: petpet
            
          - platform: linux_musl
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin: petpet
            
          - platform: windows_32
            target: i686-pc-windows-msvc
            os: windows-latest
            bin: petpet.exe
            
          - platform: windows_64
            target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: petpet.exe
            
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: nightly
          override: true

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run code build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release --target ${{ matrix.target }} --bin ${{ matrix.bin }}

      - name: Prepare assets
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ ${{ matrix.target }} != x86_64-apple-darwin ]]
          then strip ${{ matrix.bin }}
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.bin }}
